"use client";
import { useEffect, useState } from "react";
import { Mark } from "./sections";
import config from "@/public/console.json";
import benchmark from "@/public/benchmark/summary.json";
import snapshot from "@/public/snapshot.json";

const nodes = [
  {id:"target",label:"Helix Ledger",x:360,y:190,kind:"Page",description:"The controlled SaaS target connects public pricing with an authenticated dashboard."},
  {id:"pricing",label:"Pricing",x:200,y:120,kind:"Page",description:"Billing and seat controls reveal different pricing facts."},
  {id:"dashboard",label:"Dashboard",x:530,y:135,kind:"Page",description:"Authorized access reveals the Team plan’s seat usage."},
  {id:"annual-action",label:"Annual toggle",x:105,y:220,kind:"Action",description:"Switching Monthly to Annual reveals a price with annual billing context."},
  {id:"volume-action",label:"100+ seats",x:235,y:305,kind:"Action",description:"Selecting 100+ seats reveals the volume pricing condition."},
  {id:"login",label:"Authorized session",x:525,y:290,kind:"Action",description:"A signed-in session gives the walker access to the dashboard."},
  {id:"annual",label:"CA$26 / user / month",x:100,y:350,kind:"Fact",description:snapshot.facts[0].quote},
  {id:"volume",label:"From $39 / user / month",x:350,y:395,kind:"Fact",description:snapshot.facts[1].quote},
  {id:"seats",label:"25 of 30 seats",x:635,y:375,kind:"Fact",description:snapshot.facts[2].quote},
  {id:"context",label:"Billing + seat context",x:380,y:65,kind:"Context",description:"Conditions travel with the facts: annual billing, minimum seats, and authenticated access."},
];
const links=[["target","pricing"],["target","dashboard"],["pricing","annual-action"],["pricing","volume-action"],["annual-action","annual"],["volume-action","volume"],["dashboard","login"],["login","seats"],["context","pricing"],["context","dashboard"],["context","annual"],["context","volume"]];

export function HackathonShowcase(){
  const [jobId,setJobId]=useState("reveal");
  const [nodeId,setNodeId]=useState("annual");
  const [metric,setMetric]=useState<"material"|"reported">("material");
  const [recording,setRecording]=useState(false);
  const [targetUrl,setTargetUrl]=useState("");
  const [runId,setRunId]=useState("run-saturday");
  const [launchState,setLaunchState]=useState("");
  const [livePlayerUrl,setLivePlayerUrl]=useState<string|null>(null);
  const [backend,setBackend]=useState<{run?:any;borders?:any;prices?:any;matrix?:any;events?:any;sessions?:any[];connected:boolean}>({connected:false});
  const job=config.jobs.find(j=>j.id===jobId)!;
  const node=nodes.find(n=>n.id===nodeId)!;
  const selectJob=(id:string)=>{setJobId(id);setRecording(false);};
  const configuredUrl: unknown=job.playerUrl;
  const live=backend.sessions?.find((s:any)=>s.purpose===job.id||s.purpose===job.id.split("-")[0]);
  const liveUrl=live?.playerUrl;
  const playerUrl=typeof (livePlayerUrl||liveUrl||configuredUrl)==="string" && /^(https:\/\/([a-z0-9-]+\.)*steel\.dev\/|https:\/\/api\.steel\.dev\/)/.test((livePlayerUrl||liveUrl||configuredUrl) as string) ? (livePlayerUrl||liveUrl||configuredUrl) as string : null;
  useEffect(()=>{const base=(process.env.NEXT_PUBLIC_PERISCOPE_API_URL||"http://localhost:4747").replace(/\/$/,"");let cancelled=false;(async()=>{try{const paths=[`/runs/${runId}`,`/runs/${runId}/borders`,`/runs/${runId}/prices`,`/runs/${runId}/matrix`,`/runs/${runId}/events?format=json`,`/runs/${runId}/sessions`];const values=await Promise.all(paths.map(p=>fetch(base+p).then(r=>r.ok?r.json():null)));if(!cancelled)setBackend({run:values[0],borders:values[1],prices:values[2],matrix:values[3],events:values[4],sessions:values[5]?.sessions??[],connected:values.some(Boolean)});}catch{if(!cancelled)setBackend({connected:false});}})();return()=>{cancelled=true}},[runId]);
  async function launchRun(event: React.FormEvent<HTMLFormElement>){event.preventDefault();const value=targetUrl.trim();if(!/^https?:\/\//i.test(value)){setLaunchState("Enter a full URL starting with https://");return;}setLaunchState("Launching Steel jobs…");const base=(process.env.NEXT_PUBLIC_PERISCOPE_API_URL||"http://localhost:4747").replace(/\/$/,"");try{const res=await fetch(`${base}/runs`,{method:"POST",headers:{"content-type":"application/json","Idempotency-Key":`web-${Date.now()}`},body:JSON.stringify({competitor:new URL(value).hostname,url:value,pages:["/"],jobs:["surface","benchmark","reveal","borders"],countries:["CA","US","DE"],category:"demo",goal:"Recover interactive and regional evidence"})});const body=await res.json();if(!res.ok||!body.ok){setLaunchState(body.reason||"The API could not launch this run.");return;}const next=body.run?.run?.id||body.runId;if(next){setRunId(next);setLaunchState(`Run ${next} launched.`);}else setLaunchState("The API accepted the request but returned no run ID.");}catch{setLaunchState("API unavailable. Start pnpm api on port 4747 first.");}}
  return <div className="hackathon"><a href="#main" className="skip-link">Skip to content</a>
    <header className="console-header"><a className="wordmark" href="#agents"><Mark/>periscope.</a><span className="event-tag mono">UTMIST × WAT.ai / BATTLE OF THE SCHOOLS</span><nav aria-label="Main navigation"><a href="#agents">Agents</a><a href="#corpus">Corpus</a><a href="#results">Benchmark</a><a href="https://github.com/MightyTMZ/periscope">GitHub ↗</a></nav></header>
    <main id="main">
      <section id="agents" className="console-section" aria-labelledby="agents-title"><div className="console-intro"><div><div className="eyebrow">01 / AGENTS ON THE WEB · STEEL TRACK</div><h1 id="agents-title">Watch the browsers.<br/><span>Follow the evidence.</span></h1></div><p>A hackathon experiment in reading past the first page state. Open websites, reveal hidden controls, cross borders, and explore behind the login.</p></div>
        <form className="target-form" onSubmit={launchRun}><label htmlFor="target-url" className="mono">TARGET URL</label><div><input id="target-url" type="url" value={targetUrl} onChange={e=>setTargetUrl(e.target.value)} placeholder="https://competitor.example/pricing" required/><button type="submit">Open with Steel ↗</button></div><p>{launchState||"Launch a surface, reveal, borders, and benchmark run against a URL."}</p></form>
        <div className="console-toolbar mono"><span>STEEL BROWSER OPERATIONS</span><span className="mode-label">{backend.connected?"API CONNECTED":"STATIC SNAPSHOT"} · {backend.run?.run?.id||runId}</span></div>
        <div className="live-session-bar"><div className="panel-caption mono">LIVE STEEL SESSIONS · {backend.sessions?.length??0}</div>{backend.sessions?.length ? <div className="live-session-grid">{backend.sessions.map((s:any)=><button type="button" key={s.sessionId} className="live-session" onClick={()=>setLivePlayerUrl(s.playerUrl)}><span className="live-dot"/><strong>{String(s.purpose||"agent").toUpperCase()}</strong><span>{s.vantage?.country||"—"} / {s.vantage?.device||"—"}</span><small>{s.pendingWall?`WALL: ${s.pendingWall}`:s.currentUrl||"Opening page…"}</small><em>View live ↗</em></button>)}</div> : <p className="no-live-sessions">No active Steel sessions returned for this run. Launch a run with a valid Steel key; cards appear here while agents are working.</p>}</div>
        <div className="operations-grid">
          <aside className="telemetry" aria-label="Selected agent telemetry"><div className="panel-caption mono">ROUTING / SELECTED AGENT</div><h2>{job.name}</h2><p className="job-goal">{job.goal}</p>
            <svg className="routing-map" viewBox="0 0 280 145" role="img" aria-label="Steel cloud routes to configured Canada, United States, and Germany proxies"><path d="M35 72H106 M106 30V116 M106 30H212 M106 72H212 M106 116H212" fill="none" stroke="var(--structure)"/><circle cx="35" cy="72" r="6" fill="var(--text)"/><text x="10" y="98">STEEL</text>{["CA","US","DE"].map((c,i)=><g key={c}><circle cx="212" cy={30+i*43} r="5" fill={job.country===c?"var(--accent)":"var(--structure)"}/><text x="230" y={34+i*43} fill={job.country===c?"var(--accent)":"var(--muted)"}>{c}</text></g>)}</svg>
            <dl className="telemetry-fields"><div><dt>Proxy</dt><dd>{job.proxy}</dd></div><div><dt>Device</dt><dd>{job.device}</dd></div><div><dt>Access</dt><dd>{job.auth}</dd></div><div><dt>Session</dt><dd>{playerUrl?"Player linked":"Not connected"}</dd></div></dl>
            <div className="panel-caption mono">EXPECTED EXECUTION PATH</div><ol className="compact-trace">{job.steps.map((step,i)=><li key={step}><span className="mono">0{i+1}</span><span>{step}</span></li>)}</ol><p className="telemetry-note">{backend.connected?`API run ${backend.run?.run?.id||runId} · ${backend.run?.counts?.events??"—"} events · ${backend.run?.counts?.observations??"—"} observations.`:"Routing reflects the project configuration. Set NEXT_PUBLIC_PERISCOPE_API_URL to connect the API."}</p>
          </aside>
          <div className="browser-stage"><div className="agent-tabs" aria-label="Choose Steel agent">{config.jobs.map(j=><button key={j.id} type="button" aria-pressed={jobId===j.id} onClick={()=>selectJob(j.id)}>{j.name}<span>{j.country.length===2?j.country:j.id==="walker"?"AUTH":"DOM"}</span></button>)}</div>
            <div className="browser-chrome"><span className="window-dots" aria-hidden="true">● ● ●</span><span>{job.target}</span><span className="mono">{recording?"ARCHIVE":playerUrl?"STEEL PLAYER":"STATE SCHEMATIC"}</span></div>
            <div className="browser-viewport">
              {recording ? <div className="archive-view"><img src={config.recordingUrl} alt="Original Periscope Streamlit demo showing its Steel browser session grid"/><p>Original multi-browser screenshot from the repository; not a live session.</p></div> : playerUrl ? <iframe title={`${job.name} Steel browser session`} src={playerUrl} allow="clipboard-read; clipboard-write" referrerPolicy="no-referrer"/> : <div className="target-schematic"><div className="target-brand">HELIX LEDGER <span>CONTROLLED TEST TARGET</span></div>{job.id==="reveal"?<><div className="schematic-label">PRICING / RECOVERED PAGE STATE</div><h3>One toggle.<br/>A different price.</h3><div className="billing-state"><span>Monthly</span><strong>Annual</strong></div><div className="recovered-value">CA$26<small>per user / month</small></div><p>Annual billing · reported example</p></>:job.id==="walker"?<><div className="schematic-label">DASHBOARD / AUTHORIZED ACCESS</div><h3>Team plan</h3><div className="seat-count">25 <span>/ 30 seats</span></div><div className="seat-grid" aria-label="25 of 30 seats used">{Array.from({length:30},(_,i)=><i key={i} className={i<25?"used":""}/>)}</div><p>Seat usage recovered behind the login.</p></>:<><div className="schematic-label">REGIONAL PAGE / CONFIGURED VANTAGE</div><div className="country-large">{job.country}</div><h3>Same page. Different vantage.</h3><p>{job.proxy}<br/>{job.device}</p><div className="regional-empty">No captured regional price in this snapshot.</div></>}<span className="schematic-disclaimer mono">RECONSTRUCTED EVIDENCE / NOT A BROWSER RECORDING</span></div>}
            </div>
            <div className="browser-status"><div><span className="mono">OBJECTIVE</span><p>{job.goal}</p></div><button type="button" className="archive-button" aria-pressed={recording} onClick={()=>setRecording(!recording)}>{recording?"Back to selected agent":"View original demo capture"} ↗</button></div>
            <div className="agent-strip">{config.jobs.filter(j=>["reveal","ca","walker"].includes(j.id)).map(j=><button key={j.id} type="button" onClick={()=>selectJob(j.id)} aria-pressed={jobId===j.id}><span className="mono">{j.name}</span><strong>{j.result}</strong><small>{j.detail}</small></button>)}</div>
          </div>
        </div>
      </section>
      <section id="corpus" className="console-section corpus-section" aria-labelledby="corpus-title"><div className="console-section-title"><div><div className="eyebrow">02 / THE KNOWLEDGE CORPUS</div><h2 id="corpus-title">Every fact has a way back.</h2></div><p>Pages → actions → observations → context.<br/>Select a node to inspect the connection.</p></div><div className="corpus-layout"><div className="graph-region"><div className="graph-legend mono"><span>○ PAGE</span><span>◇ ACTION</span><span>● FACT</span><span>CONTEXT</span></div><svg className="knowledge-graph" viewBox="0 0 760 460" role="group" aria-label="Interactive evidence graph reconstructed from supplied examples">{links.map(([a,b])=>{const s=nodes.find(n=>n.id===a)!;const e=nodes.find(n=>n.id===b)!;return <line key={a+b} x1={s.x} y1={s.y} x2={e.x} y2={e.y} className={a===nodeId||b===nodeId?"edge selected":"edge"}/>;})}{nodes.map(n=><g key={n.id} role="button" tabIndex={0} aria-label={`Inspect ${n.label}`} aria-pressed={nodeId===n.id} onClick={()=>setNodeId(n.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setNodeId(n.id)}}} className={`graph-node ${nodeId===n.id?"selected":""}`}><circle cx={n.x} cy={n.y} r="21" fill="transparent"/><circle cx={n.x} cy={n.y} r={n.id==="target"?10:6} className={n.kind.toLowerCase()}/><text x={n.x} y={n.y+27} textAnchor="middle">{n.label}</text></g>)}</svg><p className="graph-note">Relationships from supplied examples. Illustrative layout; not an exported Qdrant graph.</p></div><aside className="node-inspector" aria-live="polite"><div className="panel-caption mono">SELECTED / {node.kind.toUpperCase()}</div><h3>{node.label}</h3><p>{node.description}</p><div className="panel-caption mono">CONNECTED TO</div><ul>{links.filter(l=>l.includes(nodeId)).map(l=>{const n=nodes.find(n=>n.id===l.find(id=>id!==nodeId))!;return <li key={n.id}><button type="button" onClick={()=>setNodeId(n.id)}>{n.label}<span>↗</span></button></li>})}</ul><div className="storage-note"><span className="mono">CORPUS ARCHITECTURE</span><p>SQLite stores observations and provenance. Qdrant supports semantic retrieval. The graph makes those relationships inspectable.</p></div></aside></div></section>
      <section id="results" className="console-section results-section" aria-labelledby="results-title"><div className="console-section-title"><div><div className="eyebrow">03 / THE BENCHMARK · {benchmark.date}</div><h2 id="results-title">65 planted facts.<br/>How much made it through?</h2></div><div className="benchmark-score">63<span>/65</span><small>IN PERISCOPE’S COLLECTED MATERIAL</small></div></div><div className="results-grid"><div><div className="metric-controls" aria-label="Benchmark metric"><button type="button" aria-pressed={metric==="material"} onClick={()=>setMetric("material")}>Facts in material</button><button type="button" aria-pressed={metric==="reported"} onClick={()=>setMetric("reported")}>Reported by Opus 4.8</button></div><div className="console-chart">{benchmark.approaches.map((a,i)=>{const v=a[metric];return <div className={`chart-row ${i===0?"highlight":""}`} key={a.name}><div className="chart-title"><strong>{a.name}</strong><span className="mono">{v??"N/A"}{v!==null&&<span className="muted"> / 65</span>}</span></div><div className="bar-track"><div style={{width:`${(v??0)/65*100}%`}}/></div></div>})}</div></div><div className="benchmark-explanation"><span className="panel-caption mono">READ THE RESULT CORRECTLY</span><p>Periscope collected <strong>63</strong> facts. Opus reported <strong>58</strong> after reading that material.</p><p>ChatGPT Astra scored <strong>38</strong> on its separately hand-scored browsing answer. It stopped at the login; it has no Opus follow-up score.</p><p>The automated comparison used local Chromium on Helix Ledger. The same browser code runs on Steel in the demo.</p><a href="/benchmark/results-2026-09-13-14-16.md" className="text-link">Read the original report ↗</a></div></div><details className="method"><summary>Full group breakdown and scoring method <span>+</span></summary><div className="table-region" tabIndex={0} role="region" aria-label="Benchmark group results"><table><caption>Cells show facts in material / reported by Opus 4.8. ChatGPT is the separately scored answer.</caption><thead><tr><th>Rubric group</th><th>Facts</th><th>Fetch</th><th>Parallel</th><th>Periscope</th><th>ChatGPT</th></tr></thead><tbody>{benchmark.groups.map(g=><tr key={g.name}><td>{g.name}</td><td>{g.total}</td><td>{g.fetch.join(" / ")}</td><td>{g.reader.join(" / ")}</td><td>{g.periscope.join(" / ")}</td><td>{g.chatgpt}</td></tr>)}</tbody></table></div><p>Matching uses case-insensitive substrings of planted text. Integration statuses require name and status. This is a controlled benchmark, not a general ranking. <a href="/benchmark/helix-rubric.json">Download rubric</a> · <a href="/benchmark/manual-results.json">ChatGPT scoring</a></p></details></section>
    </main><footer className="console-footer"><span>Periscope / Built at Battle of the Schools, September 12–13, 2026.</span><a href="https://github.com/MightyTMZ/periscope">Code, evidence, and the experiment ↗</a></footer>
  </div>;
}
